### ISSUE TITLE
Minification of CSS clip-path: url(#…) gets processed to a strange path

### ISSUE THREAD

**Issue by wassilis83** [wp-media/wp-rocket#3279]
WP Rocket version is 3.7.4

**Describe the bug**
Minification of clip-path: url(#some-svg); results in clip-path: url(../../../#some-svg); 

**To Reproduce**
1. Go to style.css of your theme folder
2. Create a rule like this clip-path: url(#some-svg) 
3. Apply minification of css in your wp-rocket config
4. Check into the inspector the minified version of this rule, it will look like this clip-path: url(../../#some-svg)

**Expected behavior**
I expect nothing more than the same original path into the minified version

**Comment by Tabrisrp** [comment]
Related issue on the Minify library: https://github.com/matthiasmullie/minify/issues/291

Not something we can fix by ourselves for now

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1497345170/259892?folderId=377611

**Comment by Mai-Saad** [comment]
I can see it fixed here https://new.rocketlabsqa.ovh/3279template/ on this branch  #3907

**Comment by mvaneijgen** [comment]
What is the status for this? Because I still have this issue and  https://new.rocketlabsqa.ovh/3279template/ is my website content, which I find really weird because I didn't know WP Rocket would rip my site and use it for testing and then reference it publicly in a GitHub Repo.

**Comment by GeekPress** [comment]
> What is the status for this?

@mvaneijgen As you can see just below the issue's title, the status is « closed ». This fix has been released in version 3.9.1.

> Because I still have this issue

If you still have the issue by using 3.9.1, thanks for providing us more details: 
- URL of your website
- A page where we can see the problem
- which CSS rules are removed

>  I didn't know WP Rocket would rip my site and use it for testing and then reference it publicly in a GitHub Repo.

Sometimes, it can happen we need to duplicate a website to be able to reproduce a problem. We shouldn't have shared our link publicly, please accept our apologies for this.

**Comment by wassy83** [comment]
for me version 3.9.1 fixed completely the issue

**Comment by mvaneijgen** [comment]
@GeekPress I see, hard to see if you are not a Github issue pro. 

I don't know if versions release schedules also release the same time as they are made, but I now see my site has updated to version 3.9.1.1 and indeed it has been fixed, maybe I lagged behind on updates, because yesterday the bug was still there and I have my site auto update their plugins

**Comment by GeekPress** [comment]
Thanks, @wassy83 and @mvaneijgen for the confirmation :)
