### ISSUE TITLE
AMP validation errors with WP Rocket JS file optimization

### ISSUE THREAD

**Issue by LuckynaSan** [wp-media/wp-rocket#3879]
**Describe the bug**
The [JavaScript file optimization option](https://jmp.sh/HXnVSZ0) in the WP Rocket plugin can[ surface these validation errors ](https://jmp.sh/xEqR4Tq) on the Web Stories URL, when the [official AMP plugin](https://wordpress.org/plugins/amp/) is enabled (and the supported template is turned on or off). 

Minify JavaScript files options on the File Optimization tab:

<img width="712" alt="116487503-20771780-a85e-11eb-85f7-0f1a6719d052" src="https://user-images.githubusercontent.com/66372350/117048822-68c08a80-ace1-11eb-9cfd-dda4984d63aa.png">

Current workarounds:

Disabling the option
Excluding the /web-stories/ url on the [Advanced Rules tab](https://jmp.sh/EkwIZrh)

**To Reproduce**

- Enable Web Stories plugin
- Enable AMP plugin
- Enable the JS Minify options in WP Rocket
- See validation errors on the URL

**Expected behavior**
No validation errors on the story URL with WP Rocket and AMP enabled.
JavaScript file optimization should be disabled for AMP and Web Stories.

**Screenshots**

**Additional context**
Web Stories and WP Rocket together are okay. Issues surface when AMP is enabled.

Web Stories Plugin Version: 1.6.0
AMP Plugin Version: 2.0.11
WP Rocket Plugin Version: 3.8.8

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by swissspidy** [comment]
While I am not sure I can properly reproduce this right now, it seems like it can't hurt to add `add_filter( 'pre_get_rocket_option_minify_js', '__return_false' );` in `AMP::disable_options_on_amp()`

**Comment by remyperona** [comment]
### Scope a solution ✅ 
The above solution seems to be spot on!

Add `add_filter( 'pre_get_rocket_option_minify_js', '__return_false' );` in `ThirdParty\Plugins\Optimization\AMP::disable_options_on_amp()`

Update the related tests

### Estimate the effort ✅
Effort `[S]`

**Comment by swissspidy** [comment]
Is there anything I can help with to move this forward?

**Comment by Mai-Saad** [comment]
The same problem (on develop) as mentioned here https://github.com/wp-media/wp-rocket/issues/4563#issuecomment-1020038533 with Web Stories 1.16.0 @piotrbak @Tabrisrp can you please check that

**Comment by swissspidy** [comment]
Let me know if I can help with anything from the Web Stories side. Off the top of my head I am not aware of any changes in 1.16.0 that would break this.

**Comment by piotrbak** [comment]
@swissspidy @Mai-Saad @Tabrisrp For any reason, the result of this conditional is different in `1.15.1` and `1.16.0` version of Web Stories (it's being checked on [wp](https://github.com/wp-media/wp-rocket/blob/9cf3d2d43d44072672eddbfdb6da16b87b0183ca/inc/ThirdParty/Plugins/Optimization/AMP.php#L51) action):
https://github.com/wp-media/wp-rocket/blob/9cf3d2d43d44072672eddbfdb6da16b87b0183ca/inc/ThirdParty/Plugins/Optimization/AMP.php#L112

In `1.16.0` we bail out and apply all our optimizations while on `1.15.1` we're able to unhook everything as expected.

**Comment by swissspidy** [comment]
On which priority are you hooking into the `wp` action? The Web Stories plugin defines the `is_amp_endpoint` function on priority 10. So it might be that your code is also running on 10, but _before_ the WS one. That can happen if one plugin is initialized before the other.

Does `'wp'                         => [ 'disable_options_on_amp', 20 ]` fix the issue?

**Comment by piotrbak** [comment]
Didn't work, unfortunately. Let's wait for @Tabrisrp opinion then...

**Comment by remyperona** [comment]
We're hooked on the default priority 10 too, so increasing our priority should do the trick

**Comment by swissspidy** [comment]
Testing with 3.10.6, I can definitely see increasing/decreasing the priority making a difference.

**Comment by remyperona** [comment]
@swissspidy Which priority value did you use?

**Comment by swissspidy** [comment]
Changing to 5 -> `function_exists( 'is_amp_endpoint' )` returns `false`
Changing to 10 -> result not certain, depends on load order, etc.
Changing to 20 -> `function_exists( 'is_amp_endpoint' )` returns `true`

So 20 should always do the trick, since the Web Stories plugin uses 10.

**Comment by remyperona** [comment]
I pushed that change to the `develop` branch @Mai-Saad

**Comment by Mai-Saad** [comment]
@Tabrisrp The problem still exists in develop branch (our optimizations are still applied). can you please check?

**Comment by engahmeds3ed** [comment]
I tried changing the action to `init` and it works but we need to bailout here when `is_admin` not to affect the real admin options of WPR:

https://github.com/wp-media/wp-rocket/blob/52aeacd03267b82f1a1f3b9b35581fcd55ccf4af/inc/ThirdParty/Plugins/Optimization/AMP.php#L112

**Comment by remyperona** [comment]
`function_exists( 'is_amp_endpoint' )` returns true when using the priority 20, but the function itself `is_amp_endpoint()` is returning `false` when on a web story page on version 1.16

**Comment by swissspidy** [comment]
That sounds odd 🤔 

For reference, the Web Stories plugin does [basically this](https://github.com/GoogleForCreators/web-stories-wp/blob/51497f589eff096ed1da69da617d6975058a97ec/includes/compat/amp.php#L29-L44):

```php
// on wp, priority 10

if ( ! function_exists( '\is_amp_endpoint' ) ) {
	function is_amp_endpoint() {
		return is_singular( 'web-story' ) && ! is_embed() && ! post_password_required();
	}
}
```

This code hasn't changed in quite a while, and definitely hasn't changed in 1.16.0

And in my quick testing (using prio 20, adding some `var_dump()` in `disable_options_on_amp()`) on 3.10.6 it definitely returns `true` on single story pages.

**Comment by remyperona** [comment]
@swissspidy What happens when both the Web Stories and the AMP plugins are enabled at the same time?

I'm guessing AMP is not checking for `is_singular( 'web-story' )`, so if it registers `is_amp_endpoint()` first, this might explain the issue we were seeing.

Are those plugins supposed to be used together, or are they exclusive?

**Comment by swissspidy** [comment]
Sounds like you have been testing this with both plugins active?

They _can_ be used together, but don't _have to_.

If both are active, the Web Stories plugin [tricks the AMP plugin into](https://github.com/GoogleForCreators/web-stories-wp/blob/176f93a9933db3024438d1c835401255ea65c9a1/includes/Integrations/AMP.php#L122-L141) making sure `is_amp_endpoint()` returns `true` when viewing a story.

And in my quick testing with 3.10.6 that seems to work as expected.

Do you see issues when both are active?

cc @westonruter in case he knows of any compat issues between AMP + Web Stories

**Comment by westonruter** [comment]
I'm not aware of any compat issues.

**Comment by swissspidy** [comment]
Just updated to 3.10.7 for testing and still don't see any issues. The `is_amp_endpoint()` check in `disable_options_on_amp()` returns `true` when viewing a single story, even when the AMP plugin is active.

**Comment by iCaspar** [comment]
I'm also not able to reproduce the `false` response locally given the hook on priority 20.
On a desktop browser, it returns false -- but that presumably wouldn't be an amp enabled page, so I expect false in that environment.
On a mobile, however, it returns true for me.
The below shows my var_dump on mobile with AMP in Transitional mode (last item is for `is_amp_endpoint()` result in the Rocket compat class at L:115)
<img width="400" alt="Screen Shot 2022-02-08 at 1 15 40 PM" src="https://user-images.githubusercontent.com/7462998/153050544-9325e87c-798a-4eb4-8f03-72b45e9daf7d.png">

Compare same var_dump on desktop:
<img width="772" alt="Screen Shot 2022-02-08 at 1 25 08 PM" src="https://user-images.githubusercontent.com/7462998/153051857-349cdd0c-b355-4f6b-9e4d-851dbfc9143a.png">

**Comment by iCaspar** [comment]
I think I see what is going on.
@swissspidy @westonruter see if this makes any sense.

We're checking for whether the `is_amp_endpoint()` function exists and returns true.
Given that both AMP and Web Stories is active, the function will exist by the time we get to the wp hook, pri 20. So function_exists test passes. BUT, the criteria for the function returning `true` will be different, depending on whether it's AMP's function, or Web Stories's function that has been defined. When both are in play, the Web Stories criteria that checks for whether it's a singular web-story posttype is NOT the defined function -- it has already been defined by AMP, so at that point we are using AMP's original function to determine if this is an endpoint where we should remove our optimizations. It will be the APM version of `is_amp_endpoint()` that is returning `false`. (I have not yet gone there yet to find out why it would, but apparently it does.)
It looks like adding further checks for both Web Stories is active AND then apply web-stories criteria for `is_amp_endpoint()` resolves the issue on our test site. See https://github.com/wp-media/wp-rocket/blob/ba8f66ca2d2b4e1f5c11/inc/ThirdParty/Plugins/Optimization/AMP.php#L116
