### ISSUE TITLE
PHP Warning with some exclusions in Load JavaScript Deferred

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3967]
A PHP warning is triggered with certain exclusions entered into Load JavaScript Deferred. 

`PHP Warning: preg_match(): Compilation failed: missing closing parenthesis at offset 943 in /wp-content/plugins/wp-rocket/inc/Engine/Optimization/DeferJS/DeferJS.php on line 78`

**To Reproduce**

1. Enter the following exclusions in Load JavaScript Deferred:
`gtag(`
`ga( '`
`ga('`
2. Check the error log for the above warning

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1522666492/266458?folderId=377611

Per Remy, the opening parenthesis are the issue since they are not escaped currently for this field.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1522119318/266286?folderId=377611
This customer reports that this issue prevents other exclusions in the field from working.

**Comment by mostafa-hisham** [comment]
### Reproduce the issue ✅ 
Reproduced on local test site

### Identify the root cause ✅ 
As Remy said, the opening parenthesis are the issue since they are not escaped currently for this field.

### Scope a solution ✅ 
I think it is better to escape all the characters used in regex patterns 
we can use this method [preg_quote](https://www.php.net/manual/en/function.preg-quote.php)
which escape The special regular expression characters: . \ + * ? [ ^ ] $ ( ) { } = ! < > | : - #

We need to update get_excluded function
https://github.com/wp-media/wp-rocket/blob/4b22e022aebb2517f29b5e31fd47899829256e9e/inc/Engine/Optimization/DeferJS/DeferJS.php#L193

to escape the special regular expression characters for "exclude_defer_js" field
```
		$exclude_defer_js_option= $this->options->get( 'exclude_defer_js', [] );

		foreach ( $exclude_defer_js_option as $i => $exclude ) {
			$exclude_defer_js_option[ $i ] = preg_quote($exclude, '/');
		}

		$exclude_defer_js = array_unique( array_merge( $exclude_defer_js,$exclude_defer_js_option ) );
```
And also remove the for loop that escapes only "#" for all $exclude_defer_js array

https://github.com/wp-media/wp-rocket/blob/4b22e022aebb2517f29b5e31fd47899829256e9e/inc/Engine/Optimization/DeferJS/DeferJS.php#L233-L236


### Estimate the effort ✅ 
check tests also

Effort [S]

**Comment by iCaspar** [comment]
This warning was fixed in #4502.

**Comment by Mai-Saad** [comment]
The warning is still not fixed for Defer JS nor Combine JS (fixed only for Delay JS)

**Comment by iCaspar** [comment]
The attached PR should handle invalid patterns being added here (by removing them on save and displaying the invalid pattern notice).

However, note also that for Defer JS, inline scripts that are not related to jQuery will not be excluded, as this UI exclusion list only applies to URLs to exclude. So `gtag(`, even if entered properly as `gtag\(` will not exclude the intended script if it is on the page as an inline.
