### ISSUE TITLE
WP Rocket settings not displayed when profile language is Português do Brasil

### ISSUE THREAD

**Issue by jorgemartine00** [wp-media/wp-rocket#4395]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

**To Reproduce**
1. Go to 'Profile'
2. Change Language to  'Português do Brasil'
3. Navigate to WP Rocket Settings
4. See the error "**There is a critical error on your website. Check your email for instructions.**"

**Expected behavior**
WP Rocket settings should be displayed.

**Screenshots**
https://jmp.sh/XZc9Vnc

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jorgemartine00** [comment]
https://secure.helpscout.net/conversation/1636073025/295848/

**Comment by Mai-Saad** [comment]
Working fine using 3.10 on multi and single test sites. Probably extra details is needed here.

**Comment by remyperona** [comment]
I can't replicate either on the current `trunk` and `develop` branches

**Comment by webtrainingwheels** [comment]
- https://secure.helpscout.net/conversation/1609807755/289485/
- https://secure.helpscout.net/conversation/1695810494/307679/
- https://secure.helpscout.net/conversation/1627955987/293960/
- https://secure.helpscout.net/conversation/1592868431/285647/

Customers/Rocketeers facing this issue, try replacing the existing translation file in /wp-content/plugins/wp-rocket/languages/ with this one: https://jmp.sh/sttTpFV

Or change the profile language until the issue is resolved on our end.

**Comment by remyperona** [comment]
Found the issue in the pt_BR translation file, one of the translated line used an incorrect string identifier (`%2$` instead of `%2$l`).

I updated the string directly on Transifex, and the fixed translation will be merged for the next release.

**Comment by vmanthos** [comment]
This is happening again.

The following PHP fatal error is thrown when the language is set to "Português do Brasil".
```
PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in /nas/example.com/wp-includes/formatting.php:5083
Stack trace:
#0 /nas/example.com/wp-includes/formatting.php(5083): sprintf('% ', 'Array')
#1 /nas/example.com/wp-content/plugins/wp-rocket/inc/Engine/Admin/Settings/Page.php(1597): wp_sprintf('%1$sComplemento...', '<em>', Array, '</em>')
#2 /nas/example.com/wp-content/plugins/wp-rocket/inc/Engine/Admin/Settings/Page.php(176): WP_Rocket\Engine\Admin\Settings\Page->cdn_section()
#3 /nas/example.com/wp-includes/class-wp-hook.php(303): WP_Rocket\Engine\Admin\Settings\Page->render_page('')
#4 /nas/example.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#5 /nas/example.com/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /nas/example.com/wp-admin/admin.php(259): do_action('settings_page_w...')
#7 /nas/example.com/wp-admin/options-general.php(10): require_once('/nas/content/li...')
#8 {main}
  thrown in /nas/example.com/wp-includes/formatting.php on line 508
```

In **rocket-pt_BR.po**, the following line:
`%1$sComplemento %2$ %3$s está ativo no momento. Não é necessário configurar CDN para %2$ funcionar no seu site.`

should be replaced with this:
`%1$sComplemento %2$l %3$s está ativo no momento. Não é necessário configurar CDN para %2$l funcionar no seu site.`

and for plural:
`%1$sComplementos %2$l %3$s estão ativos no momento. Não é necessário configurar CDN para %2$l funcionar no seu site.`

to this:
`%1$sComplementos %2$l %3$s estão ativos no momento. Não é necessário configurar CDN para %2$l funcionar no seu site.`

A `.zip` file of the fixed translation files can be downloaded here:
http://www.mediafire.com/view/0ps2d4ze9yp1eds/rocket-pt_BR.zip

**Ticket:** https://secure.helpscout.net/conversation/1753227651/318536?folderId=2135277

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1760180933/319898?folderId=377611

**Comment by remyperona** [comment]
Fixed on Transifex, it will be in 3.10.7

**Comment by Mai-Saad** [comment]
Can still see a problem in the msg when only Cloudflare or Sucuri is enabled on develop
![Screenshot from 2022-01-25 10-50-43](https://user-images.githubusercontent.com/76941962/150944585-c92a0da5-d657-4dbf-9a04-0881b5d473aa.png)
Can you please check @Tabrisrp?

**Comment by remyperona** [comment]
The translation update was not merged to develop yet

**Comment by remyperona** [comment]
It's merged now 👍🏼

**Comment by Mai-Saad** [comment]
@Tabrisrp CDN msg is fine now for Português do Brasil.
But can see the message mixed English/Italiano or English/Espanol while Italiano and Espanol Language.=> Do we need another GH issue for that? (for Espanol, we have extra inverted `?` for need help link as well)
![Screenshot from 2022-01-26 10-34-27](https://user-images.githubusercontent.com/76941962/151130586-7db9485c-0409-4382-8749-bc5ac647e042.png)
![Screenshot from 2022-01-26 10-43-26](https://user-images.githubusercontent.com/76941962/151131027-7300bd16-34d2-4737-b665-4fabcda8fb63.png)

**Comment by remyperona** [comment]
No we don't need to additional GH issues for that, those will be updated in Transifex when a translator is available.
