### ISSUE TITLE
Fatal error on Multisite when WP Rocket is activated in main site

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5539]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WP Rocket is activated on the main site on a multisite installation, creating a new sub site will cause a fatal error with the following log: 

```
[01-Nov-2022 11:24:37 UTC] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Table 'adm_live_cn.wp_8dzl4skjl5_578_actionscheduler_actions' doesn't exist in /var/www/html/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php:86
Stack trace:
#0 /var/www/html/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action()
#1 /var/www/html/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store()
#2 /var/www/html/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php(36): ActionScheduler_ActionFactory->single()
#3 /var/www/html/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php(37): as_schedule_single_action()
#4 /var/www/html/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/Queue in /var/www/html/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php on line 86
```
`adm_live_cn.wp_8dzl4skjl5_578_actionscheduler_actions` doesn't exit. 

The subsite is created.

The fatal error shows a white page.

WP Rocket is not activated on the network. 

WP Rocket didn't have RUCSS or Preload enabled on the main site.

Since the error was traced back to `/inc/Engine/Preload/Controller/Queue`, WP Rocket is trying to initiate preload even without it being active? 

**To Reproduce**
1. Enable WP Rocket on the main website
2. Create a new subsite on the network
3. See error

**Expected behavior**
There shouldn't be any fatal errors when a subsite is created, even if WP Rocket is activated on the main site on the network. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2027704694/372683?folderId=3864735
Ticket likely related - https://secure.helpscout.net/conversation/1992023959/364575/ (same error with Multisite enabled)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
@engahmeds3ed, any update? I can see the PR here https://github.com/wp-media/wp-rocket/pull/5547, but it's not assigned yet to a release.

**Comment by engahmeds3ed** [comment]
@DahmaniAdame 
I believe this is fixed here #5586 can u plz validate with the customers having this issue?

in this PR we are checking if `init` hook is finished so this means that Action Scheduler is ready.

**Comment by DahmaniAdame** [comment]
@engahmeds3ed the patch didn't work. The issue is still there. 
Can you have a look? https://secure.helpscout.net/conversation/2027704694/372683/

**Comment by DahmaniAdame** [comment]
@engahmeds3ed, any update on this one? https://secure.helpscout.net/conversation/2027704694/372683/

**Comment by CrochetFeve0251** [comment]
@DahmaniAdame I tried in local to reproduce the issue but everything worked well.
Do you have more information about the context on this issue ?

**Comment by DahmaniAdame** [comment]
@CrochetFeve0251 No additional context. When tested on the customer's website, the issue happened consistently. 
I can ask them to allow us to do some additional testing. Would you like to test there?

**Comment by CrochetFeve0251** [comment]
@DahmaniAdame that could be a way

**Comment by DahmaniAdame** [comment]
@CrochetFeve0251 request sent. One of the support team will let you know once the customer confirms 👍

**Comment by alfonso100** [comment]
@CrochetFeve0251 @engahmeds3ed  we have credentials on the ticket 🙏

**Comment by piotrbak** [comment]
@DahmaniAdame @alfonso100 On the provided multisite, WP Rocket **is** network activated. Could you confirm that it's a must to reproduce this issue?

**Comment by DahmaniAdame** [comment]
@piotrbak the issue happened with or without WP Rocket being network activated.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
