### ISSUE TITLE
[2.11-alpha2]: mobile_detect fatal error

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#588]
`PHP Fatal error:  Class 'Mobile_Detect' not found in /Users/lucy/Documents/Websites/www.wpthemes.dev/wp-content/plugins/wp-rocket/inc/front/process.php on line 184`

immediately upon update. 
if I deactivate and reactivate the mobile options, the error goes away.

**Comment by Tabrisrp** [comment]
Fixed by 9b97ae1

**Comment by apsolut** [comment]
we still get this in  2.11-beta1..  / latest update.
` Cannot redeclare class Mobile_Detect `

**Comment by Tabrisrp** [comment]
Can you give me the full error, or open a support ticket about it?

**Comment by apsolut** [comment]
need to re-test this again, had a problems with 2.11-beta1, but after cleaning cache and on clean install no issues to update from version 2.8.. to 2.11-beta1.  + Mobile_Detect inclusion.
If I dont open a ticket in the morning its false positive, will try to trigger it again
