### ISSUE TITLE
PHP Warning: strpos(): Empty needle in /Media/Lazyload/CSS/Subscriber.php on line 596

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6758]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
User is getting an **Empty Needle** error log, similar to [this one](https://wp-media.slack.com/archives/C056ZJMHG0P/p1717789951051269) but in a different location in the code:
`PHP Warning: strpos(): Empty needle in /data/sites/web/catitcom/checkout/master/before_autogit/www/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/CSS/Subscriber.php on line 596
`

@joejoe04 checked and nothing aside from WP Rocket is using `rocket_lazyload_excluded_src`.

**To Reproduce**
per @Miraeld 
we are in the lazyload process. within [this function](https://github.com/wp-media/wp-rocket/blob/2b088a335a85cb013d8186d2fc7e36f28d152c29/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L577)
And this warning would happen if this:
`$excluded_values = apply_filters( 'rocket_lazyload_excluded_src', [] ); `was returning [''] which means an array with an empty string.

**Expected behavior**
We could guard against this.

**Additional context**
ticket: https://secure.helpscout.net/conversation/2640151655/500142?folderId=2683093
slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1719936077098259

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
Based on this discussion: https://wp-media.slack.com/archives/C056ZJMHG0P/p1720009626990669?thread_ts=1717789951.051269&cid=C056ZJMHG0P

Should be fixed in 3.16.2 already

**Comment by piotrbak** [comment]
@alfonso100 could you confirm this with customer and reopen if it's not the case?

**Comment by joejoe04** [comment]
@piotrbak Alfonso is on holiday for a while, so I've got this ticket now.

Unfortunately, it appears not to be resolved, as they report they are still getting all of these errors after updating to 3.16.2 and clearing OCI data:

`[09-Jul-2024 08:45:18 UTC] PHP Warning: strpos(): Empty needle in /data/sites/web/catitcom/checkout/master/before_autogit/www/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php on line 381`

`[09-Jul-2024 08:45:18 UTC] PHP Warning: strpos(): Empty needle in /data/sites/web/catitcom/checkout/master/before_autogit/www/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/CSS/Subscriber.php on line 552`

`PHP Warning: strpos(): Empty needle in /data/sites/web/catitcom/checkout/master/before_autogit/www/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/CSS/Subscriber.php on line 596`

I checked and confirmed all the errors are being logged as of today and they do have 3.16.2 installed.

If someone would like to access, they can share their IP with me directly or in the Dev Escalation so they can allow-list for access to WP Admin and FTP:
https://wp-media.slack.com/archives/C056ZJMHG0P/p1717789951051269

**Comment by DennisTap** [comment]
Same message here. For us, it started after we updated to version 3.16.2.1! We did not have this issue with the previous version.
