### ISSUE TITLE
3.20 PM options are not added in DB before processing home in certain scenario

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#7661]
**Describe the bug**
PM options in the options table are not added when fresh activating WPR and not interacting with the dashboard/website

**To Reproduce**
1. Make sure that no PM options are in the DB 
2. Fresh install/ activation of WPR 3.20-alpha
3. Check DB without doing any interaction with dashboard in 2 => home page added to PM table and processed, while the PM options have not been added yet in DB options table (scheduled action may be canceled a couple of times before it works), leading to blurred home page results

**Expected behavior**
PM options added to DB before processing home page with/without doing interaction on admin after activation

**Note**
- It may also happen even if we interact with the dashboard and open WPR settings, leading to this in UI

<img width="923" height="259" alt="Image" src="https://github.com/user-attachments/assets/9c0cbbd7-b612-4ac8-a3bc-c7cbce1b4381" />

- Used snippet to mimic free https://group-onecom.slack.com/archives/C08EFCYRQ2X/p1758011511134289?thread_ts=1758007468.290449&cid=C08EFCYRQ2X
- Scheduled action may be triggered with every refresh 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/3ba63190-2eaf-4073-9541-77e0042c314c" />

**Comment by wordpressfan** [comment]
@Mai-Saad I pushed a fix that I believe should fix this also here:
https://github.com/wp-media/wp-rocket/pull/7660

Can u plz validate this? the issue was that the recurring AS task was created and cancelled many times because we were creating it with init hook, now it should be fine there and I tested it on new test site and it works.

**Comment by Mai-Saad** [comment]
on 3.20-alpha2: 
- PM added to options table before home change to inprogress so this will fix the blur issue 👍 
- Canceled Actions can still happen 

https://github.com/user-attachments/assets/4047fd1c-8c49-43f4-9741-5c4dfaa5bf1e
